services:
  - type: web
    name: hr-app-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        value: YOUR_MONGODB_URI
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://hr-app-frontend.onrender.com
      - key: NODE_ENV
        value: production
  - type: static
    name: hr-app-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://hr-app-backend.onrender.com/api
